# Generated by Django 6.0.4 on 2026-04-13 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('jobs', '0001_initial'),
        ('materials', '0001_initial'),
        ('traidingparties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='additives',
            field=models.ManyToManyField(related_name='jobs', to='materials.additive'),
        ),
        migrations.AddField(
            model_name='job',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='traidingparties.customer'),
        ),
        migrations.AddField(
            model_name='job',
            name='materials',
            field=models.ManyToManyField(related_name='jobs', to='materials.material'),
        ),
        migrations.AddField(
            model_name='job',
            name='tools',
            field=models.ManyToManyField(related_name='jobs', to='equipment.tool'),
        ),
        migrations.AddField(
            model_name='joblog',
            name='current_additive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_additive', to='materials.additive'),
        ),
        migrations.AddField(
            model_name='joblog',
            name='current_machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_machine', to='equipment.machine'),
        ),
        migrations.AddField(
            model_name='joblog',
            name='current_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_material', to='materials.material'),
        ),
        migrations.AddField(
            model_name='joblog',
            name='current_tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_tool', to='equipment.tool'),
        ),
        migrations.AddField(
            model_name='joblog',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='scraplog',
            name='job_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraps', to='jobs.joblog'),
        ),
        migrations.AddField(
            model_name='scraplog',
            name='scrap_reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraps', to='jobs.scrapreason'),
        ),
    ]
