# Generated by Django 6.0.4 on 2026-04-13 19:28

import django.db.models.deletion
import equipment.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crane_capacity', models.IntegerField(validators=[equipment.validators.min_value_validator])),
                ('number_of_silos', models.PositiveIntegerField()),
                ('is_centralised_cooling', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('clamping_force', models.IntegerField(validators=[equipment.validators.min_value_validator])),
                ('tool_width', models.FloatField(validators=[equipment.validators.min_value_validator])),
                ('tool_height', models.FloatField(validators=[equipment.validators.min_value_validator])),
                ('tool_thickness', models.FloatField(validators=[equipment.validators.min_value_validator])),
                ('moving_platen_stroke', models.FloatField(validators=[equipment.validators.min_value_validator])),
                ('injection_capacity', models.FloatField(validators=[equipment.validators.min_value_validator])),
                ('ejecting_stroke', models.FloatField(validators=[equipment.validators.min_value_validator])),
                ('number_of_ejector_cores', models.IntegerField(validators=[equipment.validators.min_value_validator])),
                ('is_in_use', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ToolRepairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_repair', models.TextField()),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('request_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('repair in progress', 'Repair in progress'), ('repair completed', 'Repair completed')], max_length=30)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='equipment.tool')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_number', models.CharField(max_length=10)),
                ('machine_model', models.CharField(max_length=20)),
                ('machine_description', models.TextField()),
                ('max_clamping_force', models.IntegerField(validators=[equipment.validators.min_value_validator])),
                ('max_tool_width', models.FloatField(validators=[equipment.validators.min_value_validator])),
                ('max_tool_height', models.FloatField(validators=[equipment.validators.min_value_validator])),
                ('max_tool_thickness', models.FloatField(validators=[equipment.validators.min_value_validator])),
                ('max_moving_platen_stroke', models.FloatField(validators=[equipment.validators.min_value_validator])),
                ('max_injection_capacity', models.FloatField(validators=[equipment.validators.min_value_validator])),
                ('max_ejecting_stroke', models.FloatField(validators=[equipment.validators.min_value_validator])),
                ('number_of_ejector_cores', models.IntegerField(validators=[equipment.validators.min_value_validator])),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.building')),
                ('compatible_tools', models.ManyToManyField(related_name='compatible_machines', to='equipment.tool')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('machine_number', 'building'), name='machine_code')],
            },
        ),
    ]
