# Generated by Django 6.0.4 on 2026-04-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='is_in_use',
            field=models.BooleanField(default=False),
        ),
    ]
