# Generated by Django 6.0.4 on 2026-04-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additive_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('additional_notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('block', 'PPC (Block Copolymer)'), ('clear', 'Clear PPR (Random Copolymer)'), ('homopolymer', 'PPH (Homopolymer)'), ('other', 'Other')], max_length=20)),
                ('mfi_mfr', models.CharField(max_length=3)),
                ('density', models.PositiveSmallIntegerField()),
                ('product_durability', models.CharField(choices=[('LOW', 'Standard - (Internal use)'), ('MED', 'Reinforced (PPC / Impact resistant)'), ('HIGH', 'Industrial/Outdoor (GF / UV-stabilised)')], max_length=10)),
                ('product_optic', models.CharField(choices=[('TRANSP', 'Transparent'), ('TRANSL', 'Translucent'), ('OPAQUE', 'Opaque')], max_length=10)),
                ('additional_notes', models.TextField()),
            ],
        ),
    ]
