# Generated by Django 6.0.4 on 2026-04-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='density',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
