# Generated by Django 6.0.4 on 2026-04-13 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QCIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField()),
                ('is_sorted', models.BooleanField(default=False)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setter_issues', to='accounts.employee')),
                ('job_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_issues', to='jobs.joblog')),
            ],
        ),
        migrations.CreateModel(
            name='QCLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_of_sample_issued', models.BooleanField(default=False)),
                ('like_fos', models.BooleanField(default=False)),
                ('have_spec_sheet', models.BooleanField(default=False)),
                ('correct_labels', models.BooleanField(default=False)),
                ('packed_correctly', models.BooleanField(default=False)),
                ('operator_sheet_signed', models.BooleanField(default=False)),
                ('runs_with_flash', models.BooleanField(default=False)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('job_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_logs', to='jobs.joblog')),
                ('qc_inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_logs', to='accounts.employee')),
            ],
        ),
    ]
