# Generated by Django 6.0.4 on 2026-04-13 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Report name')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('method_name', models.CharField(help_text='function name in reports library', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart_label_field', models.CharField(blank=True, help_text='Поле за X-оста (напр. order_id)', max_length=50)),
                ('chart_value_fields', models.CharField(blank=True, help_text='Полета за Y-оста, разделени със запетая (напр. quantity,scrap_quantity)', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReportParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Parameter name into function', max_length=255)),
                ('label', models.CharField(help_text='Parameter label for the user', max_length=255)),
                ('parameter_type', models.CharField(choices=[('date', 'Date'), ('int', 'Integer'), ('str', 'String'), ('choice', 'Choice'), ('bool', 'Boolean')], help_text='Parameter type', max_length=10)),
                ('source_model', models.CharField(blank=True, help_text='app_label.ModelName for choice parameters(optional) ', max_length=50, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='reports.reportconfiguration')),
            ],
        ),
    ]
